feat: update home page
KassandraFinance/kassandra-frontend pull request #512
Opened 2024-01-23 19:22 UTC by ChristanDaniel

## Why

Update to the new homepage.

## Changes

- feat: create NewButton component
- feat: create TransparentCard component
- feat: create DaoAssetManagement component
- refactor: update SectionCard component in Home page
- refactor: update home page hero
- feat: create PartnersMarquee component

2024-01-23 19:36 UTC, guilherme-correa-s requested changes

2024-01-23 19:36 UTC, guilherme-correa-s commented on src/Icons/Arrow-right-circle.tsx
> +import type { SvgProps } from '.'
```suggestion
import type { SvgProps } from './'
```

2024-01-23 19:36 UTC, guilherme-correa-s commented on src/components/CallToActionEndPage/index.tsx
> +type ICallToActionEndPageProps = {
```suggestion
type CallToActionEndPageProps = {
```

2024-01-23 19:36 UTC, guilherme-correa-s commented on src/components/TransparentCard/index.tsx
> +interface ITransparentCardProps {
Interface or type of default props?

2024-01-23 21:25 UTC, Tiago138 approved these changes

2024-01-25 18:09 UTC, guilherme-correa-s approved these changes
LGTM

2024-01-25 18:10 UTC, merged